language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run eslint
  - npm run build
after_success:
  # https://gist.github.com/maxrimue/16e272c4e0b8a8ac9dd5570e180e08c0
  - bash yarn.sh
  - yarn run coveralls